// API endpoint for dynamic config.js
export default function handler(req, res) {
  const protocol = req.headers['x-forwarded-proto'] || 'http';
  const host = req.headers['x-forwarded-host'] || req.headers.host;
  const apiUrl = `${protocol}://${host}`;
  
  res.setHeader('Content-Type', 'application/javascript');
  res.send(`
// Configuration file for client-side environment variables
// Dynamically generated by server

window.APP_CONFIG = {
  API_URL: '${apiUrl}',
  API_PORT: ''
};
  `);
}
